blog_app/urls.py
from blog_app.views import BlogCommentCreate, BlogDetailView, BlogListbyAuthorView, BlogListView, BloggerListView, BlogPostCreate, BlogPostUpdate, index

from django.urls import path

urlpatterns = [
    path('', index, name='index'),
    path('blogs/', BlogListView.as_view(), name='blogs'),
    path('blogger/<int:pk>', BlogListbyAuthorView.as_view(), name='blogs-by-author'),
    path('blog/<int:pk>', BlogDetailView.as_view(), name='blog-detail'),
    path('blog/<int:pk>/update', BlogPostUpdate.as_view(), name='blog-update'),
    path('bloggers/', BloggerListView.as_view(), name='bloggers'),
    path('blog/<int:pk>/comment/', BlogCommentCreate.as_view(), name='blog_comment'),
    path('blog/create/', BlogPostCreate.as_view(), name='blog-create')
]

my_blog/urls.py
from blog_app.views import RegisterFormView, UpdateProfile, UserProfile

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from blog_app.views import index, contact_form


urlpatterns = [
    path('', RedirectView.as_view(url='index/', permanent=True)),
    path('admin/', admin.site.urls),
    path('blog/', include('blog_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/register/", RegisterFormView.as_view(), name="register"),
    path("accounts/update_profile/", UpdateProfile.as_view(), name="update_profile"),
    path("accounts/my_profile/", UserProfile.as_view(), name="profile"),
    path('index/', index, name="index"),
    path('contact/', contact_form, name="contact"),
]


if settings.DEBUG:

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog_app/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.contrib.auth import get_user_model #Blog author or commenter

User = get_user_model()

class BlogAuthor(models.Model):
    """
    Model representing a blogger.
    """
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Enter your bio details here.")

    class Meta:
        ordering = ["user", "bio"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog-author instance.
        """
        return reverse('blogs-by-author', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.user.username


class BlogPost(models.Model):
    """
    Model representing a blog post.
    """
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200)
    short_text = models.CharField(max_length=200)
    full_text = models.TextField()
    image = models.ImageField(upload_to='blog/')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    is_published = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_date"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title


class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    commenter = models.CharField(max_length=200)
    comment_text = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    comment_date = models.DateTimeField(auto_now_add=True)
    commented_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    is_published = models.BooleanField(default=False)

    class Meta:
        ordering = ["-comment_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title = 75
        if len(self.comment_text) > len_title:
            titlestring = self.comment_text[:len_title] + '...'
        else:
            titlestring = self.comment_text
        return titlestring

blog_app/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class ContactFrom(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

blog_app/views.py
import datetime

from blog_app.tasks import send_email_task as celery_send_mail
from blog_app.tasks import send_email_to_author_task as celery_send_mail_to_author

from blog_app.forms import ContactFrom, RegisterForm
from blog_app.models import BlogAuthor, BlogPost, BlogComment

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect, render
from django.urls import path, reverse, reverse_lazy
from django.views import generic
from django.views.decorators.cache import cache_page

from my_blog import settings


@cache_page(20)
def index(request):
    """View function for home page of site."""
    b_count = BlogPost.objects.filter(is_published=True).annotate(blogposts_count=Count('author'))
    count = b_count.count()
    paginator = Paginator(b_count, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        'index.html',
        context={
            'page_obj': page_obj,
            'count': count,
        }
    )


def contact_form(request):
    if request.method == "POST":
        form = ContactFrom(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message_text = form.cleaned_data['message']
            celery_send_mail.delay(subject, message_text, from_email)
            messages.add_message(request, messages.SUCCESS, 'Message sent')
            return redirect('contact')
    else:
        form = ContactFrom()
    return render(
        request,
        "blog_app/contact.html",
        context={
            "form": form,
        }
    )


class RegisterFormView(SuccessMessageMixin, generic.FormView):
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_message = "Profile has been registered"
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        user = form.save()
        password = form.cleaned_data.get("password1")
        user = authenticate(username=user.username, password=password)
        login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)


class UpdateProfile(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = User
    fields = ["username", "email"]
    template_name = 'registration/update_profile.html'
    success_url = reverse_lazy("index")
    success_message = "Profile updated"

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class UserProfile(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = "registration/profile.html"

    def get_object(self, queryset=None):
        user = self.request.user
        return user

    def get_context_data(self, **kwargs):
        context = super(UserProfile, self).get_context_data(**kwargs)
        return context


class BlogListView(generic.ListView):
    """
    Generic class-based view for a list of all blogs.
    """
    model = BlogPost
    paginate_by = 5

    def get_queryset(self):
        """
        Return list of Blog objects having "is_published = True"
        """
        queryset = BlogPost.objects.filter(is_published=True)
        return queryset


class BlogListbyAuthorView(generic.ListView):
    """
    Generic class-based view for a list of blogs posted by a particular BlogAuthor.
    """
    model = BlogPost
    paginate_by = 5
    template_name = 'blog_app/blog_list_by_author.html'

    def get_queryset(self):
        """
        Return list of Blog objects created by BlogAuthor (author id specified in URL)
        """
        id = self.kwargs['pk']
        author = get_object_or_404(BlogAuthor, pk=id)
        queryset = BlogPost.objects.filter(author=author, is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        """
        Add BlogAuthor to context, so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(BlogListbyAuthorView, self).get_context_data(**kwargs)
        # Get the blogger object from the "pk" URL parameter and add it to the context
        context['blogger'] = get_object_or_404(BlogAuthor, pk=self.kwargs['pk'])
        return context


class BlogDetailView(generic.DetailView):
    """
    Generic class-based detail view for a blog.
    """
    model = BlogPost

    def get_context_data(self, **kwargs):
        comments = self.get_object().blogcomment_set.filter(is_published=True)
        # comments = BlogComment.objects.filter(is_published=True, commented_post=self.get_object())
        paginator = Paginator(comments, 5)
        try:
            page_num = int(self.request.GET.get("page", 1))
        except ValueError:
            print('incorrect page number')
        try:
            page = paginator.page(page_num)
        except ValueError:
            print('incorrect page number')
        context = super().get_context_data(**kwargs)
        context["comments"] = comments
        context["paginator"] = paginator
        context["page_obj"] = page
        context["is_paginated"] = True
        return context


class BloggerListView(generic.ListView):
    """
    Generic class-based view for a list of bloggers.
    """
    model = BlogAuthor
    paginate_by = 5


class BlogCommentCreate(generic.CreateView):
    """
    Form for adding a blog comment. Requires login.
    """
    model = BlogComment
    fields = ['commenter', 'comment_text']

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['blogpost'] = get_object_or_404(BlogPost, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """
        Add associated blog to form data before setting it as valid (so it is saved to model)
        """
        # Associate comment with blog based on passed id
        post = get_object_or_404(BlogPost, pk=self.kwargs['pk'])
        form.instance.commented_post = post

        # Sending email to helpdesk
        subject = 'new comment has been added'
        from_email = 'noreply@my_blog.com'
        message_text = post.title+' received a new comment: "'+form.cleaned_data['comment_text']+'"'
        celery_send_mail.delay(subject, message_text, from_email)

        # Sending email to author
        url = reverse('blog-detail', kwargs={'pk': self.kwargs['pk'], })
        link = f"{settings.SCHEMA}://{settings.DOMAIN}{url}"
        subject = 'new comment has been added to your post'
        author_email = [post.author.user.email]
        message_text = post.title+' received a new comment: "'+form.cleaned_data['comment_text']+'" '+link
        celery_send_mail_to_author.delay(subject, message_text, author_email)

        # Call super-class form validation behaviour
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self):
        """
        After posting comment return to associated blog.
        """
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'], })


class BlogPostCreate(LoginRequiredMixin, generic.CreateView):
    model = BlogPost
    fields = ['title', 'short_text', 'full_text', 'created_date', 'published_date', 'image', 'is_published']
    initial = {
        'published_date': datetime.datetime.now(),
    }

    def form_valid(self, form):
        author = BlogAuthor.objects.get(user_id=self.request.user.id)
        form.instance.author = author
        subject = 'new post has been created'
        from_email = 'noreply@my_blog.com'
        message_text = author.user.username+' created new post "'+form.cleaned_data['title']+'"'
        celery_send_mail.delay(subject, message_text, from_email)
        return super(BlogPostCreate, self).form_valid(form)


class BlogPostUpdate(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = BlogPost
    fields = ['title', 'short_text', 'full_text', 'created_date', 'published_date', 'image', 'is_published']
    initial = {
        'published_date': datetime.datetime.now(),
    }
    template_name = 'blog_app/blogpost_update.html'
    success_message = "Blog post was updated"

    def get_success_url(self):
        """
        After posting comment return to associated blog.
        """
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'], })

templates/blog_app/blog_list_by_author.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blogger: {{blogger}}</h1>

    <h3>Bio</h3>

    <p>{{blogger.bio}}</p>



    {% if blogpost_list %}
    <h3>Blogs list</h3>
    <ul>

      {% for blogpost in blogpost_list %}
          <li>
          <img src="{{ blogpost.image.url }}" class="img-responsive" style="width: 30px; height:30px;" />
          <a href="{{ blogpost.get_absolute_url }}">{{ blogpost.title }}</a>
          ({{blogpost.published_date}}) —
          {{ blogpost.short_text }}
          </li>
          <br>
      {% endfor %}

    </ul>

    {% else %}
      <p>This blogger hasn't posted anything yet.</p>
    {% endif %}
{% endblock %}

templates/blog_app/blogauthor_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All bloggers</h1>

    {% if blogauthor_list %}
    <ul>

      {% for author in blogauthor_list %}
      <li>
        <a href="{% url 'blogs-by-author' author.pk %}">{{ author }}</a> - {{ author.bio }}
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no bloggers yet.</p>
    {% endif %}       
{% endblock %}

templates/blog_app/blogcomment_form.html
{% extends "base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blog-detail' blogpost.pk %}">{{blogpost.title}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

templates/blog_app/blogpost_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <a href="{% url 'blog-update' blogpost.pk %}">Update this post</a>
    <h1>{{ blogpost.title }}</h1>
    <p><strong>Published</strong> {{ blogpost.published_date }}</p>
    <p><strong>Author:</strong> <a href="{% url 'blogs-by-author' blogpost.author.pk %}">{{ blogpost.author }}</a></p>
    <p><img src="{{ blogpost.image.url }} "class="img-responsive" alt={{ blogpost.image }}></p>
    <p><strong>Full text:</strong></p>
    <p style="white-space:pre-wrap;">{{ blogpost.full_text }}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h5>{{ comments.count }} comments</h5>
        {% for comment in page_obj %}
            <hr>
            <p>{{comment.commenter}} ({{comment.comment_date}}) - {{comment.comment_text}}</p>
        {% endfor %}
        <hr>
        <p><a href="{% url 'blog_comment' blogpost.pk %}">Add a new comment</a></p>
    </div>

{% endblock %}

templates/blog_app/blogpost_form.html
{% extends "base_generic.html" %}

{% block content %}

  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit"/>

  </form>
{% endblock %}

templates/blog_app/blogpost_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>All posts</h1>
<hr>

    {% if blogpost_list %}
    <ul>

      {% for blogpost in blogpost_list %}
          <li>
          <img src="{{ blogpost.image.url }}" class="img-responsive" style="width: 30px; height:30px;" />
          <a href="{{ blogpost.get_absolute_url }}">{{ blogpost.title }}</a>
          {{ blogpost.short_text }}... —
          published by <a href="{% url 'blogs-by-author' blogpost.author_id %}"> {{ blogpost.author }}</a>
          at {{ blogpost.published_date }}
          </li>
          <br>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no published blogs.</p>
    {% endif %}
{%  endblock %}

templates/blog_app/blogpost_update.html
{% extends "base_generic.html" %}

{% block content %}

    {% if request.user.is_authenticated and blogpost.author_id == request.user.id %}
        <form method="POST" class="form-group">
            {% csrf_token %}
            <table>
              {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-success">Update</button>
        </form>
    {% else %}
    <p>Access Denied - only the author can edit the post</p>
    {% endif %}

{% endblock %}

templates/blog_app/contact.html
{% extends "base_generic.html" %}

{% block br_cr %}{{ block.super }}/<a href="{% url 'contact' %}">Contact</a>{% endblock %}

{% block content %}
  <h1>Contact Us</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
      <button type="submit">Send</button>
    </div>
  </form>
{% endblock %}