my_blog/urls.py
from blog_app.views import RegisterFormView, UpdateProfile, UserProfile

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from blog_app.views import index, contact_form


urlpatterns = [
    path('', RedirectView.as_view(url='index/', permanent=True)),
    path('admin/', admin.site.urls),
    path('blog/', include('blog_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/register/", RegisterFormView.as_view(), name="register"),
    path("accounts/update_profile/", UpdateProfile.as_view(), name="update_profile"),
    path("accounts/my_profile/", UserProfile.as_view(), name="profile"),
    path('index/', index, name="index"),
    path('contact/', contact_form, name="contact"),
]


if settings.DEBUG:

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog_app/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.contrib.auth import get_user_model #Blog author or commenter

User = get_user_model()

class BlogAuthor(models.Model):
    """
    Model representing a blogger.
    """
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Enter your bio details here.")

    class Meta:
        ordering = ["user", "bio"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog-author instance.
        """
        return reverse('blogs-by-author', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.user.username


class BlogPost(models.Model):
    """
    Model representing a blog post.
    """
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200)
    short_text = models.CharField(max_length=200)
    full_text = models.TextField()
    image = models.ImageField(upload_to='blog/')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    is_published = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_date"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title


class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    commenter = models.CharField(max_length=200)
    comment_text = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    comment_date = models.DateTimeField(auto_now_add=True)
    commented_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    is_published = models.BooleanField(default=False)

    class Meta:
        ordering = ["-comment_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title = 75
        if len(self.comment_text) > len_title:
            titlestring = self.comment_text[:len_title] + '...'
        else:
            titlestring = self.comment_text
        return titlestring

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}My blog{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">My Blog</span>
  </div>
</nav>

<div class="container-fluid">

  {% if messages %}
    <div class="row">
      <div class="col-sm-12">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
            <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}
              {{ message.tags|title }}{% endif %}!</strong> {{ message }}
          </div>
        {% endfor %}
      </div>
    </div>
  {% endif %}

  <br>
  <div class="row">
    <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'blogs' %}">All blog posts</a></li>
          <li><a href="{% url 'bloggers' %}">All authors</a></li>
          <li><a href="{% url 'contact' %}">Contact</a></li>
        </ul>

        <ul class="sidebar-nav">
          {% if user.is_authenticated %}
            <li>Logged as: {{ user.get_username }}</li>
            <li><a href="{% url 'blog-create' %}">Create new post</a></li>
            <li><a href="{% url 'profile' %}">My profile</a></li>
            <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
            <li><a href="{% url 'register' %}?next={{ request.path }}">Register</a></li>
          {% endif %}
        </ul>

        {% if user.is_staff %}
          <hr/>
          <ul class="sidebar-nav">
            <li>Staff tools:</li>
            {% if perms.catalog.can_mark_returned %}
              <li><a href="{% url 'admin:app_list' app_label='blog_app' %}">Admin module</a></li>
            {% endif %}
          </ul>
        {% endif %}

      {% endblock %}
    </div>
    <div class="col-sm-10 ">
      {% block content %}{% endblock %}

      {% block pagination %}
        {% if is_paginated %}
          <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
              <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
              {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
            </span>
          </div>
        {% endif %}
      {% endblock %}

    </div>
  </div>

</div>
</body>
</html>

templates/index.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Welcome to <em>My Blog</em></h1>

    <p>There are {{ count }} recently published posts</p>

    {% for post in page_obj %}
        <ul>
            <li>
                <b>{{ post.author }}</b> published <b>"{{ post.title }}"</b> post
                that has {{ post.blogcomment_set.count }} comments </li>
        </ul>
    {% endfor %}

    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}